### ISSUE TITLE
Update symbol `BOYSHP50` (Safe Water 'Paper Chart' symbol), `BOYSPH60`, `BOYSPR60` and `BOYPIL60`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#317] opened 2024-02-08 16:35 UTC
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/158

Update symbol once created (slanted color bands)

**Comment by DavidGrant-NIWC** [comment] 2024-03-28 20:20
Symbols are available: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/158#issuecomment-2025057738

**Comment by DavidGrant-NIWC** [comment] 2024-04-09 14:52
Ensure metadata, CSS reference, etc. are correct during update.

**Comment by mikan66** [comment] 2024-04-17 15:35
Essentially duplicate of 316.

**Closed by mikan66** 2024-04-17 15:35 UTC
Labels: PC 1.3.0
