### ISSUE TITLE
QualityOfBathymetricData :  DisplayPriority 4

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#242] opened 2023-06-13 14:23 UTC
David
It looks like Display Priority stays as it is in S-52 => 4
if confirmed , Proposal to move display priority to 12
Pol

**Comment by DavidGrant-NIWC** [comment] 2023-06-13 14:37
Duplicate of #50

**Closed by DavidGrant-NIWC** 2023-06-13 14:37 UTC
Labels: duplicate
