### ISSUE TITLE
new ECDIS Chart 1 custom feature Chart 1 Feature [DCEG GAP 1.3.0_2.0.0 Row 5]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#402] opened 2024-06-26 18:31 UTC
Add support for new ECDIS Chart 1 custom feature Chart 1 Feature.

**Comment by DavidGrant-NIWC** [comment] 2024-06-26 19:13
duplicate of #389

**Closed by DavidGrant-NIWC** 2024-06-26 19:13 UTC
Labels: duplicate, PC 1.4.0
