### ISSUE TITLE
Measured Distance Value (row 61 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#65] opened 2022-05-09 20:26 UTC
![image](https://user-images.githubusercontent.com/4913543/167491059-bc796ab8-7b91-4578-a637-ce1af89b594c.png)

Rule update DistanceMark.lua.

NOTE: Sanchez, Alvaro MR:
Display the abbreviation of the unit of measurement in use preceeding waterwayDistance.

![image](https://user-images.githubusercontent.com/4913543/167490932-7b9db833-bfd2-423a-9683-d896b916b393.png)

![image](https://user-images.githubusercontent.com/4913543/167491003-11a28edf-ae9a-4633-a6f6-2ae9d3b9acea.png)

(DistanceMark.zip) New symbol here from Holger: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/39  

From duplicate issue #35
categoryOfDistanceMark was removed in FC 1.0.2 and distanceMarkVisible was added.

**Comment by DavidGrant-NIWC** [comment] 2022-05-19 20:09
Duplicate of #35

**Comment by mikan66** [comment] 2022-05-24 13:27
Dave - you closed this without updating the symbol to DISMAR06.

**Comment by mikan66** [comment] 2022-10-14 14:21
Consolidate all "Measured distance value (Distance mark)" related open issues here.  Most recent guidance is below.

https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/39#issuecomment-1189865921

**Comment by DavidGrant-NIWC** [comment] 2022-10-27 14:00
Directed to update abbreviations: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/39

**Closed** 2022-10-27 14:02 UTC
Labels: enhancement, test, PC 1.0.2

**Comment by DavidGrant-NIWC** [comment] 2023-09-13 19:02
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/fb54b072-701c-47ea-80fb-db0c3b099f68)

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0008/7

**Comment by DavidGrant-NIWC** [comment] 2023-12-06 22:18
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/43f06c7f-e1b0-4c5e-83cf-f66fc0dec53f)
