### ISSUE TITLE
Orientation of light flare needs to be fixed in some situations

### ISSUE THREAD

**Issue by IngaFjellanger** [iho-ohi/S-101_Portrayal-Catalogue#116] opened 2022-07-27 11:02 UTC
The LightFlareAndDescription  script does not work correctly when it creates an instruction to draw the light flare symbol. It happens when flood light or spotlight feature coincides with Light All Around feature with the same colour attribute values. For example below, it considers that there are two features Lights All Around with identical colour and rotates a flare symbol to 45 degrees. 

Current presentation
![LightFlareCurrent](https://user-images.githubusercontent.com/70318960/181231561-f5a9005e-36d6-4acd-b7d0-559c3aa40261.png)

Presentation with fixed LightFlareAndDescription.lua  script
![LightFlareFixed](https://user-images.githubusercontent.com/70318960/181231716-24328d1b-335d-4a67-9342-66d99bcc73f1.png)

**Comment by IngaFjellanger** [comment] 2022-07-27 11:03
[LightFlare_comment#2.zip](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/9197780/LightFlare_comment.2.zip)
This is how we suggest to amend the lua script

**Comment by DavidGrant-NIWC** [comment] 2022-07-27 18:15
Please make sure you are using the latest portrayal catalog. If you agree with the comments below I will close this as a duplicate of #62.

* The 1st change has already been incorporated
![image](https://user-images.githubusercontent.com/62906211/181341262-225b4be4-caab-4785-bd99-0e96e948d8bf.png)

  * See last comment on #62
  * Note https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/67479b1cdf007fdf91c5739cb6e7852881d5b1d5

* The 2nd change is unnecessary:
![image](https://user-images.githubusercontent.com/62906211/181341534-1cc583ed-824b-4f26-9620-b52c084571d4.png)
  * LightFlareAndDescription is not called for flood lights, spotlights, strip lights, or major lights; therefore categoryOfLight[1] will never contain 8, 9, or 11

* The 3rd change does not agree with the S-52 CSP and would need S-101 PSWG approval
![image](https://user-images.githubusercontent.com/62906211/181342289-f1eb384c-fc32-49a0-8b72-928e57ba06a3.png)
![image](https://user-images.githubusercontent.com/62906211/181342712-5267da4f-14ff-466c-b1eb-8a2445888527.png)

**Comment by mikan66** [comment] 2022-10-12 21:35
Does anyone have comments to this, otherwise I will move to close this issue?

**Comment by alvarosanuy** [comment] 2022-10-16 22:17
@IngaFjellanger - Can you please confirm you support NIWC's implementation as per Dave's entry above?? Enhancements to S-52 must be lodged as new PsWG GitHub issues for discussion in that forum first.

**Comment by IngaFjellanger** [comment] 2022-10-18 11:39
Hi,
1 OK
2 LightFlareAndDescription is not called for flood lights, spotlights, strip lights, or major lights; that is correct. But what happens if there is another light in the same position? Then we have to consider this.
3 You are right about S-52. But just to be on the safe side, could there be an alternating red and green light? It is not standard use of lights, but can such a non standard situation occur?

**Comment by DavidGrant-NIWC** [comment] 2022-10-18 14:31
> 1 OK
 2 LightFlareAndDescription is not called for flood lights, spotlights, strip lights, or major lights; that is correct. But what happens if there is another light in the same position? Then we have to consider this.

A _flareAngle_ should be encoded [by the production software] for both lights. See **DCEG 30.2 flare angle**:
`Required where there is more than one light encoded on an instance of point spatial geometry.`

> 3 You are right about S-52. But just to be on the safe side, could there be an alternating red and green light? It is not standard use of lights, but can such a non standard situation occur?

DCEG 30.2 applies whenever the lights are co-located. There could be an S-58 check for a missing or unknown _flareAngle_ in the case of co-located lights - not sure if this is already present.

**Comment by mikan66** [comment] 2022-10-18 17:50
@alvarosanuy - Please assign a PC version if this remains open.

**Comment by alvarosanuy** [comment] 2022-10-19 00:11
I would suggest closing this issue and ask @IngaFjellanger to create 1 or 2 new PsWG Github Issues to further discuss an enhancement/change to existing S-52 practices. I would label those issues as '**PC 1.2.0 or late**r'.

**Comment by LeoKuzmin** [comment] 2022-10-19 13:37
@DavidGrant-NIWC  
The _flareAngle_ attribute is not mandatory for a Light features therefore we should drawn flares correctly without this attribute for different cases.
2. There is simple scenario where in on point there are two _LightAllAlround_ feature. One of them has one of values {8,9,11} of _categoryOfLight_, e.g. Spot light. When we draw this light we don't call the LightFlareAndDescription script and show the symbol LIGHTS82. Another _LightAllAround_ is navigational light. It is drawn by the LightFlareAndDescription script, where in the line 30 we collect an array 'associatedFeatures' with all features placed in the same point. This array also includes the Spot light. As a result the script set an orientation of the flare to 45 degrees. I am sure we don't need rotate flare in this case.
I believe The above quote from DCEG 30.2 refers to navigational lights only.
4. "alternating" is Light Characteristic, so it is one Light instance with two or tree colours. And I suppose it would be useful to draw flares for each colour with different orientations.

**Comment by DavidGrant-NIWC** [comment] 2022-10-27 14:14
Closing this issue.

As Alvaro noted above this requires PsWG discussion/approval prior to PC implementation.

Please open a PsWG issue in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues or request that Alvaro do so if you would like to propose this enhancement for co-located lights.

**Closed by DavidGrant-NIWC** 2022-10-27 14:14 UTC
